---
apiVersion: scheduler.punchplatform.io/v2
kind: Plan
metadata:
  name: processing-aggregation-plan
  labels:
    app: processing-aggregation-plan
spec:
  kind: BatchPunchline
  interval: 10s
  #cron: "* * * * *"
  checkpointRef:
    name: processing-aggregation
    kind: ConfigMap
  dates:
    from:
      offset: "-10h45m"
      format: "2006-01-02T15:04:05-0700"
  templateSpec:
    labels:
      app: aggregation
    containers:
      serviceAccount: admin-user
      resourcesInitContainer:
        image: ghcr.io/punchplatform/resourcectl:8.1-dev
        imagePullPolicy: IfNotPresent
        resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
      applicationContainer:
        image: ghcr.io/punchplatform/punchline-java:8.1-dev
        env:
          - name: JDK_JAVA_OPTIONS
            value: "-Xms100m -Xmx450m"
    dag:
      - id: input
        type: elasticsearch
        kind: source
        settings:
          http_hosts:
            - host: elasticsearch-master.doc-store
              port: 9200
              scheme: http
          index: default-haproxy-2023.11.16
          query: >
            {
              "query":{
                "match_all":{}
              }
            }
        out:
          - id: output
            table: documents
      - id: output
        kind: sink
        type: show