---
# This is a plan that will be executed by the scheduler. It will run the punchline
# defined in the templateSpec section. The punchline will be executed every 10 seconds.
# The checkpointRef section is used to store the last execution date of the punchline.
#
# The punchline simply reads a fraction of the documents from the default-haproxy-* index
# and writes them to the default-aggregation-* index.
apiVersion: scheduler.punchplatform.io/v2
kind: Plan
metadata:
  name: processing-aggregation-plan
  annotations:
    prometheus.io/push-gateway: http://artifacts-server.artifacts-server:4245
spec:
  kind: BatchPunchline
  interval: 10s
  # Instead of interval you can use a cron expression
  checkpointRef:
    name: processing-aggregation
    kind: ConfigMap
  dates:
    from:
      offset: "-10h45m"
      format: "2006-01-02T15:04:05-0700"
  templateSpec:
    containers:
      serviceAccount: admin-user
      resourcesInitContainer:
        image: ghcr.io/punchplatform/resourcectl:8.1-dev
        imagePullPolicy: IfNotPresent
        resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
      applicationContainer:
        image: ghcr.io/punchplatform/punchline-java:8.1-dev
        env:
          - name: JDK_JAVA_OPTIONS
            value: "-Xms100m -Xmx450m"
    dag:
      - id: input
        type: elasticsearch
        kind: source
        settings:
          debug: true
          http_hosts:
            - host: elasticsearch-master.doc-store
              port: 9200
              scheme: http
          security:
            ssl:
            credentials:
              username: elastic
              password: elastic
          index: default-haproxy-*
          query: >
            {
            "query": {
                "match": {
                "log.syslog.hostname": "server1.board.com"
                }
            }
            }
          size: 50
          from: 0
          scroll: true
          scroll_keep_alive: "10m"
          scroll_size: 50
          max_concurrent_shard_requests: 5
          mode: source
        out:
          - id: output
            table: documents
            columns:
              - name: doc_field
                type: string

      - id: output
        kind: sink
        type: elasticsearch
        settings:
          show: false
          http_hosts:
            - host: elasticsearch-master.doc-store
              port: 9200
          security:
            credentials:
              username: elastic
              password: elastic
          index:
            type: daily
            prefix: default-aggregation-
          document:
            json_column: doc_field