---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: processing-raw
  labels:
    tenant: default
    channel: processing
    app: raw
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    #metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    #metrics.punchplatform.com/pushIntervalSeconds: '10'
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx1g -Dpunchplatform.every_period_secs=10"
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.1-dev
      resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
  dag:
    - id: input
      kind: source
      type: kafka
      settings:
        show: true
        start_offset_strategy: latest
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topics: logs-input
      out:
        - id: print
          table: logs
          columns:
            - name: data
              type: string
            - name: _ppf_id
              type: string
            - name: _ppf_local_port
              type: int
            - name: _ppf_local_host
              type: string
    - id: print
      kind: function
      type: punchlet
      settings:
        debug: true
        punchlets:
          - "{ debug(root); }"
      out:
        - id: elastic
          table: logs
          columns:
            - name: data
              type: string
    - id: elastic
      kind: sink
      type: elasticsearch
      settings:
        show: true
        http_hosts:
          - host: elasticsearch-master.doc-store
            port: 9200
        security:
          credentials:
            username: elastic
            password: qoZKuibf96*U_r-ILhbW
        index:
          type: daily
          prefix_column: default-raw
        document:
          json_column: data
          extra_fields:
            - type: date
              name: ts
