---
apiVersion: punchline.punchplatform.io/v2
kind: SparkPunchline
metadata:
  name: wine-quality-pyspark
  annotations:
    prometheus.io/scrape: 'false'
    prometheus.io/port: '0'
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    metrics.punchplatform.com/pushGatewayIntervalSeconds: '10'
spec:
  containers:
    serviceAccount: admin-user
    applicationContainer:
        image: ghcr.io/punchplatform/punchline-pyspark:8.1-dev
        imagePullPolicy: IfNotPresent
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.1-dev
      resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
  dependencies:
  - "model:io.model:wine:1.0"
  - "additional-pex:io.model:wine-model-dependencies:1.0"
  engineSettings:
      spark.app.name: wine-quality-pyspark
      spark.kubernetes.authenticate.driver.serviceAccountName: admin-user
      spark.kubernetes.container.image.pullPolicy: IfNotPresent
      spark.sql.execution.arrow.pyspark.enabled: "true"
      spark.executorEnv.ARROW_PRE_0_15_IPC_FORMAT: "1"
      spark.hadoop.fs.s3a.access.key: minioadmin
      spark.hadoop.fs.s3a.secret.key: minioadmin
      spark.hadoop.fs.s3a.endpoint: http://minio.object-store:9000
      spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
      spark.hadoop.fs.s3a.path.style.access: "true"
  dag:
    - id: input
      kind: source
      type: file
      settings:
        path: s3a://data/winequality-red.csv 
        options:
          inferSchema: true
          header: true
      out:
        - id: sql_processing
          table: data

    - id: sql_processing
      kind: function
      type: sql
      settings:
        udfs:
          - model_name: io.model:wine:1.0
            name: prediction
            schema_ddl: String
        statements:
        - statement: SELECT * FROM input_data
          output_table_name: input
        # Apply prediction
        - statement: >
            SELECT *, prediction(`fixed acidity`, `volatile acidity`, `citric acid`, `residual sugar`, `chlorides`, `free sulfur dioxide`, `total sulfur dioxide`, `density`, `pH`, `sulphates`, `alcohol`) as prediction
            FROM input
          output_table_name: prediction

      out:
        - id: show
          table: prediction

              
    - id: show
      kind: sink
      type: show
      settings:
        show_schema: true
