---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: indexing-logs
  labels:
    tenant: default
    channel: indexing
    app: indexing-logs
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx512m -Dpunchplatform.every_period_secs=10"
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.1-dev
      resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
  dag:
    - id: input
      kind: source
      type: kafka
      settings:
        start_offset_strategy: last_committed
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topics: default-haproxy,default-stormshield,default-microsoft
        value.format: json
      out:
        - id: elastic
          table: logs
          columns:
            - name: data
              type: string
            - name: _ppf_id
              type: string
            - name: _ppf_topic
              type: string

    - id: elastic
      kind: sink
      type: elasticsearch
      settings:
        http_hosts:
          - host: elasticsearch-master.doc-store
            port: 9200
        security:
          credentials:
            username: elastic
            password: elastic
        index:
          type: daily
          prefix_column: _ppf_topic
        document:
          json_column: data
          id_column: _ppf_id
          extra_fields:
            - type: date
              name: ts
