apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: radar-simulator-locations
  annotations:
    prometheus.io/scrape: 'false'
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    metrics.punchplatform.com/pushIntervalSeconds: '10'
  labels:
    app: radar-simulator-logs
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx1g -Dpunchplatform.every_period_secs=10"
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.1-dev
      resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
  dag:
    - id: simulator
      type: generator_source
      kind: source
      engine_settings: 
        throughput: 30
      settings:
        messages_size: -1
        fields:
          - name: objectId
            type: random
            min: 0
            max: 10
          - name: lon
            type: random
            min: 0
            max: 180
          - name: lat
            type: random
            min: 0
            max: 180
          - name: alt_avion
            type: random
            min: 50
            max: 12000
          - name: freq
            type: random
            min: 1000
            max: 30000
          - name: ocean
            type: random
            min: 0
            max: 1
          - name: timestamp
            type: timestamp
            format: 'MMM dd HH:mm:ss'
        columns:
          - id: "%{objectId}"
            lon: "%{lon}"
            lat: "%{lat}"
            alt: "%{alt_avion}"
            frequence: "%{freq}"
            is_ocean: "%{ocean}"
            timestamp: "%{timestamp}"
          - id: "%{objectId}"
            lon: "%{lon}"
            lat: "%{lat}"
            alt: "0"
            frequence: "%{freq}"
            is_ocean: "%{ocean}"
            timestamp: "%{timestamp}"
      out:
        - id: sink
          table: locations
          columns:
            - name: id
              type: string
            - name: lon
              type: string
            - name: lat
              type: string
            - name: alt
              type: string
            - name: frequence
              type: string
            - name: is_ocean
              type: string
            - name: timestamp
              type: string
    - id: sink
      kind: sink
      type: kafka
      settings:
        show: false
        debug: false
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topic: locations-input