apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: sensor-east
  annotations:
    prometheus.io/scrape: 'false'
    punchplatform.thalesdigital.io/platform: platform
    devices.punchplatform.com/id: zone-europe-west1-rennes-east
    devices.punchplatform.com/version: "3.1"
    devices.punchplatform.com/inactivityTimeout: "30"
    devices.punchplatform.com/refreshIntervalSeconds: "10"
    devices.punchplatform.com/vendor: "iot.punchplatform.com"
    devices.punchplatform.com/adminUrl: "http://artifacts-server.punch:8080/v1/devices/device"
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.punch:8080
    metrics.punchplatform.com/pushIntervalSeconds: '10'
spec:
  containers:
    applicationContainer:
      # This image field is required even if outside Kubernetes. It clearly indicates the
      # binary version of your punchline engine. Here the java 8.1-dev release. 
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx1g -Dpunchplatform.every_period_secs=10"
  dag:
    - id: data
      type: generator_source
      kind: source
      engine_settings: 
        throughput: 30
      settings:
        messages_size: -1
        fields:
          - name: objectId
            type: random
            min: 0
            max: 10
          - name: lon
            type: random
            min: 0
            max: 180
          - name: lat
            type: random
            min: 0
            max: 180
          - name: alt_avion
            type: random
            min: 50
            max: 12000
          - name: freq
            type: random
            min: 1000
            max: 30000
          - name: ocean
            type: random
            min: 0
            max: 1
          - name: timestamp
            type: timestamp
            format: 'MMM dd HH:mm:ss'
        columns:
          - id: "%{objectId}"
            lon: "%{lon}"
            lat: "%{lat}"
            alt: "%{alt_avion}"
            frequence: "%{freq}"
            is_ocean: "%{ocean}"
            timestamp: "%{timestamp}"
          - id: "%{objectId}"
            lon: "%{lon}"
            lat: "%{lat}"
            alt: "0"
            frequence: "%{freq}"
            is_ocean: "%{ocean}"
            timestamp: "%{timestamp}"
      out:
        - id: sink
          table: locations
          columns:
            - name: id
              type: string
            - name: lon
              type: string
            - name: lat
              type: string
            - name: alt
              type: string
            - name: frequence
              type: string
            - name: is_ocean
              type: string
            - name: timestamp
              type: string
    - id: sink
      type: http
      kind: sink
      engine_settings:
        tick_row_frequency_ms: 1000
      settings:
        # Activating debug will print useful information, without skipping the sending of the data.
        debug: false
        # Activating show make the sink pretty print the data, but skips the sending.
        show: false
        # The punch encoding format make HTTP body contains the table, row schemas together with the
        # encoded rows.
        encoding_codec: punch
        best_effort: false
        bulk_size: 1000
        bulk_interval: 1000
        url: http://ingestion.punchplatform.com:8070/