---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: cyber-indexing-alerts
  labels:
    app: cyber-indexing-alerts
  annotations:
    prometheus.io/scrape: 'false'
    prometheus.io/port: '0'
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    metrics.punchplatform.com/pushIntervalSeconds: '10'

spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx512m -Dpunchplatform.every_period_secs=10"
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.1-dev
      resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
  dag:
    - id: input
      kind: source
      type: kafka
      settings:
        show: false
        start_offset_strategy: last_committed
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topics: default-alerts
        value.format: json
      out:
        - id: spreading
          table: logs
          columns:
            - name: alerts
              type: string
            - name: _ppf_id
              type: string

    - id: spreading
      kind: function
      type: punchlet
      settings:
        punchlets:
          - "{
              if ([logs][alerts].exists()) {
                Tuple result;
                for (Tuple t : [logs][alerts].asArray()) {
                  Tuple alert;
                  alert:[logs][data] = t;
                  result.append(alert);
                }
                root:/ = result;
              }
              else {
                  root.empty();
              }
            }"
      out:
        - id: elastic-alerts
          table: logs
          columns:
            - name: data
              type: string

        - id: elastic_errors
          table: logs
          columns:
            - name: _ppf_error_document
              type: string

    - id: elastic-alerts
      kind: sink
      type: elasticsearch
      settings:
        show: true
        http_hosts:
          - host: elasticsearch-master.doc-store
            port: 9200
        security:
          credentials:
            username: elastic
            password: elastic
        index:
          type: daily
          prefix: default-alerts-
        document:
          json_column: "data"
          extra_fields:
            - type: date
              name: 'ts'

    - id: elastic_errors
      kind: sink
      type: elasticsearch
      settings:
        show: true
        http_hosts:
          - host: elasticsearch-master.doc-store
            port: 9200
        security:
          credentials:
            username: elastic
            password: elastic
        index:
          type: daily
          prefix: default-errors-
        document:
          json_column: _ppf_error_document
          extra_fields:
            - type: date
              name: 'ts'