---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: cyber-processing-forward
  labels:
    app: cyber-processing-forward
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    metrics.punchplatform.com/pushIntervalSeconds: '10'
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx1g -Dpunchplatform.every_period_secs=10"
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.1-dev
      resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
  dag:
    - id: input
      kind: source
      type: kafka
      settings:
        show: true
        value.format: json
        start_offset_strategy: latest
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topics: logs-input
      out:
        - id: print
          table: logs
          columns:
            - name: data
              type: string
            - name: _ppf_id
              type: string
            - name: _ppf_local_port
              type: int
            - name: _ppf_local_host
              type: string
    - id: print
      kind: function
      type: punchlet
      settings:
        debug: false
        punchlets:
          - "{ debug(root); }"
      out:
        - id: forward
          table: logs
          columns:
            - name: data
              type: string
    - id: forward
      kind: sink
      type: http
      engine_settings:
        tick_row_frequency_ms: 1000
      settings:
        # Activating debug will print useful information, without skipping the sending of the data.
        debug: false
        # Activating show make the sink pretty print the data, but skips the sending.
        show: false
        # The punch encoding format make HTTP body contains the table, row schemas together with the
        # encoded rows.
        encoding_codec: punch
        best_effort: false
        bulk_size: 1000
        bulk_interval: 1000
        url: https://punch.free.beeceptor.com:9095/
