---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: cyber-processing-parsing
  labels:
    app: cyber-processing-parsing
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    metrics.punchplatform.com/pushGatewayIntervalSeconds: '10'
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx1g -Dpunchplatform.every_period_secs=10"
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.1-dev
      resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
  dependencies:
    - punch-parsers:com.github.punchplatform:starter-parsers:3.0.0
  dag:
    - id: input
      kind: source
      type: kafka
      settings:
        show: false
        value.format: json
        start_offset_strategy: latest
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topics: logs-input
      out:
        - id: parser
          table: logs
          columns:
            - name: data
              type: string
            - name: _ppf_id
              type: string
            - name: _ppf_local_port
              type: int
            - name: _ppf_local_host
              type: string
    - id: parser
      kind: function
      type: parser
      settings:
        #debug: true
        root_tuple_column: data
        parsers:
          # haproxy
          - resources:
              - name: ecs_groks
                url: groks
                type: file
                format: grok2
              - name: ecs_v1
                url: /opt/punch/resources/ecs-v1
                type: file
                format: grok2
            punchlets:
              - "{ [event][original] = root; }"
              - "{ [data_processing][unparsed_data] = [event][original]; }"
              - core/syslog.punch
              - haproxy/parser.punch
              - "{ table:[haproxy] = row; }"
          # apache
          - resources:
              - name: http_codes
                format: json
                type: file
                url: apache/http_codes.json
            punchlets:
              - "{ [event][original] = root; }"
              - "{ [data_processing][unparsed_data] = [event][original]; }"
              - apache/parser.punch
              - "{ table:[apache] = row; }"
      out:
        - id: kafka_errors
          table: _ppf_errors
          columns:
            - name: _ppf_error_document
              type: string
        - id: enrich
          table: haproxy
          columns:
            - name: data
              type: string
            - name: _ppf_id
              type: string
            - name: _ppf_local_port
              type: int
            - name: _ppf_local_host
              type: string
        - id: enrich
          table: apache
          columns:
            - name: data
              type: string
            - name: _ppf_id
              type: string
            - name: _ppf_local_port
              type: int
            - name: _ppf_local_host
              type: string
    - id: enrich
      kind: function
      type: punchlet
      settings:
        debug: false
        root_tuple_column: data
        punchlets:
          - "{ [event][id] = row:[_ppf_id]; }"
      out:
        - id: kafka_haproxy
          table: haproxy
          columns:
            - name: data
              type: string
            - name: _ppf_id
              type: string
            - name: _ppf_local_port
              type: int
            - name: _ppf_local_host
              type: string
        - id: kafka_apache
          table: apache
          columns:
            - name: data
              type: string
            - name: _ppf_id
              type: string
            - name: _ppf_local_port
              type: int
            - name: _ppf_local_host
              type: string
        - id: kafka_errors
          table: _ppf_errors
          columns:
            - name: _ppf_error_document
              type: string
    - id: kafka_haproxy
      kind: sink
      type: kafka
      settings:
        show: false
        show_max_length: 128
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topic: default-haproxy
        format: json
    - id: kafka_apache
      kind: sink
      type: kafka
      settings:
        show: false
        show_max_length: 128
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topic: default-apache
        format: json
    - id: kafka_errors
      kind: sink
      type: kafka
      settings:
        show: false
        show_max_length: 128
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topic: default-errors
        format: json