apiVersion: punchline.punchplatform.io/v2
kind: BatchPunchline
metadata:
  name: apache-rust
  annotations:
    prometheus.io/scrape: 'false'
    punchplatform.thalesdigital.io/platform: platform
    devices.punchplatform.com/id: zone-europe-west1-apache-rust-h1
    devices.punchplatform.com/version: "3.1"
    devices.punchplatform.com/inactivityTimeout: "30"
    devices.punchplatform.com/refreshIntervalSeconds: "10"
    devices.punchplatform.com/vendor: "iot.punchplatform.com"
    devices.punchplatform.com/adminUrl: "http://artifacts-server.punch:8080/v1/devices/device"
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.punch:8080
    metrics.punchplatform.com/pushGatewayIntervalSeconds: '10'
spec:
  dependencies: 
    - wasm:com.github.punchplatform:detection:3.0.0
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/rline:0.1-dev
  dag:
    - id: input
      kind: source
      type: generator
      settings:
        interval: 1000
        messages_column:
          - data: "<14> Nov 23 10:30:45 webserver1.example.com apache: 192.168.1.100 - - [23/Nov/2023:10:30:45 +0000] \"GET /phpmyadmin HTTP/1.1\" 404 1234"
          - data: "<14> Nov 23 10:30:45 webserver1.example.com apache: 192.168.1.100 - - [23/Nov/2023:10:30:45 +0000] \"GET /wp-admin HTTP/1.1\" 404 1234"
          - data: "<14> Nov 23 10:30:45 webserver1.example.com apache: 192.168.1.100 - - [23/Nov/2023:10:30:45 +0000] \"GET /index.html HTTP/1.1\" 200 1234"
      out:
        - id: sink
          table: logs
          columns:
            - name: data
              type: string
    - id: sink
      type: http
      kind: sink
      engine_settings:
        tick_row_frequency_ms: 1000
      settings:
        debug: false
        bulk_size: 1000
        url: http://ingestion.punchplatform.com:8090/


