apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: hopital-sevigne
  annotations:
    prometheus.io/scrape: 'false'
    punchplatform.thalesdigital.io/platform: platform
    devices.punchplatform.com/id: zone-europe-west1-hopital-sevigne
    devices.punchplatform.com/version: "3.1"
    devices.punchplatform.com/inactivityTimeout: "30"
    devices.punchplatform.com/refreshIntervalSeconds: "10"
    devices.punchplatform.com/vendor: "iot.punchplatform.com"
    devices.punchplatform.com/adminUrl: "http://artifacts-server.punch:8080/v1/devices/device"
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.punch:8080
    metrics.punchplatform.com/pushGatewayIntervalSeconds: '10'
spec:
  source:
    geo:
      location:
        lat: 48.12957389809394
        lon: -1.6270817976457972
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx1g -Dpunchplatform.every_period_secs=10"
  dag:
    - id: data
      type: generator_source
      kind: source
      settings:
        fields:
          - name: snare_event_count
            type: random
            min: 0
            max: 6000
          - name: hour
            type: random
            min: 0
            max: 23
          - name: min
            type: random
            min: 0
            max: 59
          - name: sec
            type: random
            min: 0
            max: 59
          - name: computer_name
            type: list
            content:
              - server-1
              - fihe3nok1606.nsn-intra.net
              - prod-ds7892
              - HPNodeCore2485
              - WOSServer-158
              - CODrioSAM-12
              - kiz4amp4567.kiz-hp.net
              - chs89amp4521.chs-amp.net
              - rpa12amp4857.chs-amp.net
              - fhi32amp4957.fhi.net
              - dap32amp47.chs-amp.net
              - prodServer-45.nt-prod.com
              - HPNodeCore8455
              - WOSServer-NOPROD-892
              - CODrioSAP-12.ext.com
          - name: security_id
            type: list
            content:
              - S-1-3-2
              - S-1-3-3
              - S-1-3-4
              - S-1-4
              - S-1-5
              - S-1-5-1
              - S-1-5-10
              - S-1-5-11
              - S-1-5-12
              - S-1-5-13
              - S-1-5-14
              - S-1-5-15
              - S-1-5-17
              - S-1-5-18
              - S-1-5-19
              - S-1-5-2
          - name: account_name
            type: list
            content:
              - "-"
              - APT8785$
              - IZP5848$
              - HSP3752$
              - ODE8445$
              - OSF5845$
              - PAK7541$
          - name: account_domain
            type: list
            content:
              - "-"
              - SPO-IBV
              - AZEF-FRS
              - DFOR-PLZ
              - CPMD-FDS
              - LMED-NTA
              - SPE-CLO
          - name: command_line
            type: list
            content:
              - C:\system32\ schtasks create wscript e:vbscript
              - Import-Module "$Env:Temp\OpenView\bin\win64\opcmsg.exe
              - ipmo $Env:Temp\win64\enex.exe
              - ipmo '$Env:Appdata\core\creo.exe
              - C:\PROGRA~1\HP OpenView\bin\win64\opcmsg.exe
              - C:\Windows\System32\RuntimeBroker.exe
              - C:\Windows\System32\bin\win64\adrc.exe
              - C:\run txt:makecab a.cab
              - Import-Module $Env:Appdata\trust.exe
              - ipmo C:\Users\Public\srcs.exe
              - C:\Windows\System32\bin\win64\adrc.exe
              - C:\Windows\System32\bin\win64\hoprc.exe
              - C:\Windows\System32\svchost.exe
              - C:\Windows\System32\notepad.exe
              - C:\danger.exe --install --start-with-win --silent
              - C:\Windows\System32\bin\win64\diag.exe
              - Import-Module $Env:Temp\ext4.exe
              - C:\atk.exe create wscript schtasks e:vbscript
              - C:\WINDOWS\system32\cmd.exe /C cmd.exe /c echo J9kzQ2Y0qO |C:\ProgramData\anydesk.exe --set-password
              - C:\Import-Module '$Env:Temp\ATTACK.danger
              - C:\run.exe -noni -ep bypass $path
              - C:\Windows\System32\rundll32.exe
              - Import-Module $Env:Temp\rvs.bin
              - C:\Windows\explorer.exe
              - C:\system32\fields schtasks create wscript e:vbscript C:\root\conf
              - Import-Module $Env:Temp\axv.s
              - C:\Import-Module --path C:\Windows\romp --start-with-win --silent
              - C:\Windows\System32\ipconfig.exe
              - C:\Windows\System32\mimikatz.exe
              - C:\Windows\System32\nbtstat.exe
              - C:\Windows\System32\net.exe
              - C:\Windows\System32\netsh.exe
              - C:\Windows\System32\nslookup.exe
              - C:\Windows\System32\ping.exe
              - C:\Windows\System32\quser.exe
              - C:\Windows\System32\qwinsta.exe
              - C:\Windows\System32\reg.exe
              - C:\Windows\System32\runas.exe
              - C:\Windows\System32\sc.exe
              - C:\Windows\System32\schtasks.exe
              - C:\Windows\System32\ssh.exe
              - C:\Windows\System32\systeminfo.exe
        interval: 10000
        messages_size: -1
        messages:
          - 'MSWinEventLog\t0\tSecurity\t%{snare_event_count}\tThu Oct 12 %{hour}:%{min}:%{sec} 2023\t4688\tMicrosoft-Windows-Security-Auditing\t-\\-\tN/A\tSuccess Audit\t%{computer_name}\tProcess Creation\t\tA new process has been created.    Creator Subject:   Security ID:  %{security_id}   Account Name:  %{account_name}   Account Domain:  %{account_domain}   Logon ID:  0x3E7    Target Subject:   Security ID:  %{security_id}   Account Name:  %{account_name}   Account Domain:  %{account_domain}   Logon ID:  0x0    Process Information:   New Process ID:  0x1814   New Process Name: C:\\Windows\\process.exe   Token Elevation Type: TokenElevationTypeDefault (1)   Creator Process ID: 0x598   Process Command Line: %{command_line}   100.00%\\\" START: 04/29/2021 07:30:00 (-b 1619670600 -e 1619670600)\" msg_grp=Performance    Token Elevation Type indicates the type of token that was assigned to the new process in accordance with User Account Control policy.    Type 1 is a full token with no privileges removed or groups disabled.  A full token is only used if User Account Control is disabled or if the user is the built-in Administrator account or a service account.    Type 2 is an elevated token with no privileges removed or groups disabled.  An elevated token is used when User Account Control is enabled and the user chooses to start the program using Run as administrator.  An elevated token is also used when an application is configured to always require administrative privilege or to always require maximum privilege, and the user is a member of the Administrators group.    Type 3 is a limited token with administrative privileges removed and administrative groups disabled.  The limited token is used when User Account Control is enabled, the application does not require administrative privilege, and the user does not choose to start the program using Run as administrator.\t333525\n'

      out:
        - id: sink
          table: logs
          columns:
            - name: data
              type: string

    - id: sink
      type: http
      kind: sink
      engine_settings:
        tick_row_frequency_ms: 1000
      settings:
        debug: false
        show: false
        encoding_codec: punch
        best_effort: false
        bulk_size: 1000
        bulk_interval: 1000
        url: http://ingestion.punchplatform.com:8090/