---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: radar-ingestion-http
  labels:
    app: radar-ingestion-http
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    metrics.punchplatform.com/pushGatewayIntervalSeconds: '10'
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      imagePullPolicy: IfNotPresent
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx300m -Dpunchplatform.every_period_secs=10"
  dag:
    # The HTTP source act as your receiver HTTP server, receiving payload from
    # external devices or applications.
    - id: input
      kind: source
      type: http_source
      settings:
        debug: false
        url: "http://0.0.0.0:8070"
      out:
        - id: sink
          table: locations
          columns:
          - name: id
            type: string
          - name: lon
            type: string
          - name: lat
            type: string
          - name: alt
            type: string
          - name: frequence
            type: string
          - name: is_ocean
            type: string
          - name: timestamp
            type: string  
    # The records are inserted into Kafka. The table name (here locations) is not
    # part of the encoding data. Only the columns name and values.
    # In the following configuration rows are encoded using a binary key value
    # format for efficiency. Punch also supports JSON or AVRO encoding.
    - id: sink
      kind: sink
      type: kafka
      settings:
        show: false
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topic: locations-input
    
