---
# This is a plan. Plans are cron-like punch facilities. A plan runs the punchline
# defined in the templateSpec section. Here the punchline will be executed every 10 seconds.
# The checkpointRef section is used to store the last execution date of the punchline.
#
# The punchline simply reads a fraction of the documents from the default-haproxy-* index
# and writes them to the default-aggregation-* index.
apiVersion: scheduler.punchplatform.io/v2
kind: Plan
metadata:
  name: fligths-aggregation
  annotations:
    prometheus.io/push-gateway: http://artifacts-server.artifacts-server:4245
spec:
  kind: BatchPunchline
  interval: 10s
  # Instead of interval you can use a cron expression
  checkpointRef:
    name: processing-aggregation
    kind: ConfigMap
  dates:
    from:
      offset: "+02h00m"
      format: "2006-01-02T15:04:05-0700"
  templateSpec:
    containers:
      serviceAccount: admin-user
      resourcesInitContainer:
        image: ghcr.io/punchplatform/resourcectl:8.1-dev
        imagePullPolicy: IfNotPresent
        resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
      applicationContainer:
        image: ghcr.io/punchplatform/punchline-java:8.1-dev
        env:
          - name: JDK_JAVA_OPTIONS
            value: "-Xms100m -Xmx450m"
    dag:
      - id: input
        type: elasticsearch
        kind: source
        settings:
          debug: false
          http_hosts:
            - host: elasticsearch-master.doc-store
              port: 9200
              scheme: http
          security:
            ssl:
            credentials:
              username: elastic
              password: elastic
          index: default-haproxy-*
          query: >
            {
                "query": {
                    "bool": {
                        "must": [
                            {
                                "match": {
                                    "log.syslog.hostname": "server1.board.com"
                                }
                            },
                            {
                                "range": {
                                    "@timestamp": {
                                        "gte": "now-10m/m",
                                        "lte": "now/m"
                                    }
                                }
                            }
                        ]
                    }
                }
            }
          scroll: true
          scroll_keep_alive: "10m"
          scroll_size: 1000
          max_concurrent_shard_requests: 5
          mode: source
        out:
          - id: output
            table: documents
            columns:
              - name: doc_field
                type: string

      - id: output
        kind: sink
        type: elasticsearch
        settings:
          show: false
          http_hosts:
            - host: elasticsearch-master.doc-store
              port: 9200
          security:
            credentials:
              username: elastic
              password: elastic
          index:
            type: daily
            prefix: default-aggregation-
          document:
            json_column: doc_field