---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: radar-indexing-logs
  labels:
    app: radar-indexing-logs
  annotations:
    prometheus.io/scrape: 'false'
    prometheus.io/port: '0'
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    metrics.punchplatform.com/pushIntervalSeconds: '10'

spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx512m -Dpunchplatform.every_period_secs=10"
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.1-dev
      resourcesProviderUrl: http://artifacts-server.artifacts-server:4245
  dag:
    - id: input
      kind: source
      type: kafka
      settings:
        debug: false
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topics: locations-input
        value.format: lumberjack
        start_offset_strategy: latest
      out:
        - id: elastic
          table: locations
          columns:
          - name: id
            type: string
          - name: lon
            type: string
          - name: lat
            type: string
          - name: alt
            type: string
          - name: frequence
            type: string
          - name: is_ocean
            type: string
          - name: timestamp
            type: string

    - id: elastic
      kind: sink
      type: elasticsearch
      settings:
        show: false
        http_hosts:
          - host: elasticsearch-master.doc-store
            port: 9200
        security:
          credentials:
            username: elastic
            password: qoZKuibf96*U_r-ILhbW
        index:
          type: daily
          prefix: radar-west-
        document:
          column_fields:
          - lon
          - lat
          - alt
          - frequence
          - is_ocean
          - timestamp
