---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: radar-archiving-locations
  labels:
    app: radar-archiving-locations
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    metrics.punchplatform.com/pushGatewayUrl: http://artifacts-server.artifacts-server:4245
    metrics.punchplatform.com/pushIntervalSeconds: '10'
spec:
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.1-dev
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms100m -Xmx1g -Dpunchplatform.every_period_secs=10"
  dag:
    - id: input
      kind: source
      type: kafka
      load_control:
        throughput: 10000
        max_pending_row_number: 1000
        row_timeout_secs: 0
      settings:
        bootstrap.servers: kooker-kafka-kafka-brokers.processing:9092
        topics: locations-input
        value.format: lumberjack
        start_offset_strategy: latest
      out:
      - id: sink
        table: locations
        columns:
        - name: id
          type: string
        - name: lon
          type: string
        - name: lat
          type: string
        - name: alt
          type: string
        - name: frequence
          type: string
        - name: is_ocean
          type: string
        - name: timestamp
          type: string
        # # The archive sink requires you to include the partition id column
        # - name: _ppf_partition_id
        #   type: long
        # # as well as read record offset. 
        # - name: _ppf_partition_offset
        #   type: long
        # - name: _ppf_id      
        #   type: string

    - id: sink
      kind: sink
      type: archive
      engine_settings:
        tick_row_frequency_ms: 10000
      settings:
        # Two strategies are supported: at_least_once and one_by_one.
        # See below for more explanations.
        strategy: at_least_once
        # The destination store. File, S3, and ceph destinations re supported.
        destination: 'http://minio.object-store:9000'
        access_key: minioadmin
        secret_key: minioadmin
        # To control the naming layout of your archives.
        # See detailed explanations below.
        file_prefix_pattern: "%{topic}/locations-%{date:hh}.%{date:mm}"
        
        # The pool is the top level folder.
        pool: archives
        
        # The topic is a second level folder.
        topic: locations
        
        # The compression format
        compression_format : GZIP
        encoding: csv
        add_header: true
        separator: ","
        
        create_root: true
        # The column to be used as a timestamp indicator
        timestamp_column: timestamp
        
        # The number of rows cont each batch archive file
        batch_size: 1000
        
        # The expiration timeout to flush incomplete batches
        batch_expiration_timeout: 5s
    
    
            